#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then to run this script, type that shell name before the whole
#       command line, like:
#
#           ksh gradlew ...
#
#       Busybox and similar reduced shells will NOT work, because this script
#       requires all of these POSIX shell features:
#         * functions;
#         * expansions «$var», «${var}», «${var:-default}», «${var+SET}»,
#           «${var#prefix}», «${var%suffix}», and «$( cmd )»;
#         * compound commands having a testable exit status, especially «case»;
#         * various built-in commands including «command», «set», and «ulimit».
#
#   (2) Important for understanding:
#
#       The initialisation of this script is complex, but the purpose is
#       simple: to define (1) «APP_HOME» as the directory where this script
#       lives, and (2) «CLASSPATH» as a list of jar files within the
#       «gradle/wrapper» subdirectory; and then (3) to execute Java, passing
#       that Classpath and the list of these same jar files as the arguments.
#
#   (3) Specific Gradle wrapper features:
#
#       The «gradle-wrapper.jar» is a small jar file that understands how to
#       download the full Gradle distribution.
#
#       If you want to use a proxy, you can pass arguments to the wrapper
#       via the «GRADLE_OPTS» environment variable.
#
#       If you want to debug the wrapper itself, you can pass arguments
#       via the «JAVA_OPTS» environment variable.
#
##############################################################################

#
#   Shell functions.
#

#   Print a warning message to standard error.
warn () {
    echo "$*"
}

#   Print an error message to standard error, then exit.
die () {
    echo
    echo "$*"
    echo
    exit 1
}

#   Log the given message at the INFO level.
log () {
    if [ "$INFO" = "true" ] ; then
        echo "$*"
    fi
}

#
#   Initialisation.
#

#   Set execution shell if currently unset.
#   (This is the name of the executable being run, e.g., «sh» or «bash».)
#   (It is used by «ps» to determine the process command name.)
if [ -z "$SHELL" ] ; then
    SHELL="/bin/sh"
fi

#   Set app name.
APP_NAME="Gradle"

#   Set app base name.
APP_BASE_NAME=`basename "$0"`

#   Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

#   Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD="maximum"

#   Warn if the operating system is not fully supported info.
#   (This is just a warning, it does not stop execution.)
#   (We only check the OS if we are not running in Cygwin.)
if [ "$cygwin" = "false" ] ; then
    #   Check the OS.
    case "`uname`" in
        CYGWIN* )
            cygwin=true
            ;;
        Darwin* )
            darwin=true
            ;;
        MINGW* )
            msys=true
            ;;
        MSYS* )
            msys=true
            ;;
    esac
fi

#   For Cygwin, ensure paths are in UNIX format before anything is touched.
if $cygwin ; then
    [ -n "$JAVA_HOME" ] && JAVA_HOME=`cygpath --unix "$JAVA_HOME"`
    [ -n "$CLASSPATH" ] && CLASSPATH=`cygpath --path --unix "$CLASSPATH"`
fi

#   For Msys, ensure paths are in UNIX format before anything is touched.
if $msys ; then
    [ -n "$JAVA_HOME" ] && JAVA_HOME=`cygpath --unix "$JAVA_HOME"`
    [ -n "$CLASSPATH" ] && CLASSPATH=`cygpath --path --unix "$CLASSPATH"`
fi

#
#   Determine the Java command to use to start the JVM.
#

if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses via jre/sh/java definition of JAVA_HOME
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD="java"
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

#
#   Determine the location of the Gradle wrapper jar file.
#

#   Resolve the location of the «gradlew» script.
#   (This is the directory containing this script.)
#   (It may be a symlink, so we must follow it.)
#   (We also must handle spaces in the path.)
#   (We use «ls -ld» to determine if it is a symlink.)
#   (We use «expr» to extract the link target.)
#   (We use «cd» and «pwd» to determine the absolute path.)

#   Use «ls -ld» to determine if it is a symlink.
#   (We use «ls -ld» because it works on all POSIX systems.)
#   (We use «ls -ld» because it handles spaces in the path.)
#   (We use «ls -ld» because it handles relative paths.)
#   (We use «ls -ld» because it handles absolute paths.)
#   (We use «ls -ld» because it handles paths with special characters.)

#   Resolve the location of the «gradlew» script.
PRG="$0"
while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG=`dirname "$PRG"`"/$link"
    fi
done
SAVED="`pwd`"
cd "`dirname "$PRG"`" >/dev/null
APP_HOME="`pwd -P`"
cd "$SAVED" >/dev/null

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

#
#   Determine the location of the Java command to use to start the JVM.
#

#   If the user has set the JAVA_OPTS environment variable, use that.
#   Otherwise, use the default JVM options.
if [ -n "$JAVA_OPTS" ] ; then
    #   We want to append the default options to the user-specified options.
    #   We want to do this because the user-specified options may override
    #   the default options.
    #   We want to do this because the user may want to add options to the
    #   default options.
    JVM_OPTS="$JAVA_OPTS $DEFAULT_JVM_OPTS"
else
    JVM_OPTS="$DEFAULT_JVM_OPTS"
fi

#   If the user has set the GRADLE_OPTS environment variable, use that.
#   Otherwise, use the default Gradle options.
if [ -n "$GRADLE_OPTS" ] ; then
    #   We want to append the default options to the user-specified options.
    #   We want to do this because the user-specified options may override
    #   the default options.
    #   We want to do this because the user may want to add options to the
    #   default options.
    #   We want to do this because the user may want to add options to the
    #   default options.
    GRAM_OPTS="$GRADLE_OPTS"
fi

#
#   Run Gradle.
#

exec "$JAVACMD" \
    $JVM_OPTS \
    $GRAM_OPTS \
    -classpath "$CLASSPATH" \
    org.gradle.wrapper.GradleWrapperMain \
    "$@"
